---
swagger: "2.0"
info:
  description: No description
  version: 1.0.0
  title: Reflection
paths:
  /methods:
    get:
      summary: Gets the methods defined for every control type
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        202:
          description: Status 200
          schema:
            $ref: './schemas/schema.yml#/definitions/Methods'
        404:
          description: Status 404
          schema:
            $ref: './schemas/schema.yml#/definitions/Error'
        500:
          description: Status 500
          schema:
            $ref: './schemas/schema.yml#/definitions/Error'
      deprecated: false
