definitions:
  Methods:
    type: object
    properties:
      mobile_number:
        type: string
        minLength: 10
      customer_first_name:
        type: string
        minLength: 2
  Error:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
parameters:
  applicationId:
    name: applicationId
    required: true
    type: string
    in: header